In [2]:
import numpy as np

In [4]:
print(np.__version__, np.__config__)

1.25.2 <module 'numpy.__config__' from '/home/chris/.conda/envs/numpy_100/lib/python3.11/site-packages/numpy/__config__.py'>


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
Z = np.zeros(10)
Z.size*Z.itemsize

80

In [23]:
# python -c "import numpy; numpy.info(numpy.add)"

In [25]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [32]:
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [33]:
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [41]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

In [55]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
Z = np.random.random((3,3,3))
Z

array([[[0.96131891, 0.14886662, 0.93420085],
        [0.86183522, 0.56504386, 0.81067819],
        [0.20111379, 0.33105907, 0.15984799]],

       [[0.4231392 , 0.53906172, 0.58233471],
        [0.54911044, 0.25282145, 0.77472713],
        [0.71351102, 0.82992121, 0.20361932]],

       [[0.84855783, 0.70380362, 0.25289249],
        [0.07070486, 0.82419236, 0.77675483],
        [0.8703588 , 0.17012796, 0.42244047]]])

In [81]:
Z = np.random.random((10,10))
Z.min(), Z.max()

(0.008106892546665079, 0.9916511890687484)

In [83]:
Z = np.random.random(10)
Z.mean()

0.4960458504470708

In [90]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [104]:
0 * np.nan

nan

In [105]:
np.nan == np.nan

False

In [106]:
np.inf > np.nan

False

In [107]:
np.nan - np.nan

nan

In [108]:
np.nan in set([np.nan])

True

In [109]:
0.3 == 3 * 0.1

False